### ISSUE TITLE
Upgrading to python3.4 gives error

### ISSUE THREAD

**Issue by gabn88** [mbi/django-rosetta#138]
After upgrading to python3.4 my site breaks. I have tried to fix it, but could not get my head around is. I hope there are some smart people here at github who can help. Much appreciated!

Internal Server Error: /
Traceback (most recent call last):
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/gabn88/webapps/production_v2/production/framework/framework/views.py", line 11, in home
    return render(request, "site1/home.html")
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(_args, *_kwargs),
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/loader.py", line 174, in render_to_string
    return t.render(context_instance)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/defaulttags.py", line 527, in render
    return self.nodelist.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 522, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 292, in _populate
    for name in pattern.reverse_dict:
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python3.4/functools.py", line 428, in wrapper
    result = user_function(_args, *_kwds)
  File "/home/gabn88/webapps/production_v2/lib/python3.4/Django-1.7.9-py3.4.egg/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/gabn88/lib/python3.4/rosetta/views.py", line 14, in <module>
    from rosetta.conf import settings as rosetta_settings
  File "/home/gabn88/lib/python3.4/rosetta/conf/settings.py", line 23, in <module>
    import goslate  # NOQA
  File "/home/gabn88/lib/python3.4/goslate.py", line 33, in <module>
    import concurrent.futures
  File "/home/gabn88/lib/python3.4/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/gabn88/lib/python3.4/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

**Comment by mbi** [comment]
Try this: `pip3 uninstall futures`

**Comment by gabn88** [comment]
Nice! It works :)
