### ISSUE TITLE
Exception raised because of unresolved variables "do_django" and "do_rosetta"

### ISSUE THREAD

**Issue by Ecno92** [mbi/django-rosetta#181]
- Which version of Django are you using?: 
1.10.5

- Which version of django-rosetta are you using?:
0.7.12

- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
Yes

If was running Django in debug mode and found this in the logs:
```
app_1          | 2017-03-10 10:19:28,168 DEBUG [django.template:929] base 9 139644053845888 Exception while resolving variable 'do_django' in template 'rosetta/languages.html'.
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
app_1          |     current = current[bit]
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 75, in __getitem__
app_1          |     raise KeyError(key)
app_1          | KeyError: 'do_django'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 891, in _resolve_lookup
app_1          |     if isinstance(current, BaseContext) and getattr(type(current), bit):
app_1          | AttributeError: type object 'RequestContext' has no attribute 'do_django'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
app_1          |     current = current[int(bit)]
app_1          | ValueError: invalid literal for int() with base 10: 'do_django'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
app_1          |     (bit, current))  # missing attribute
```

and

```
app_1          | 2017-03-10 10:19:27,984 DEBUG [django.template:929] base 9 139644053845888 Exception while resolving variable 'do_rosetta' in template 'rosetta/languages.html'.
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 885, in _resolve_lookup
app_1          |     current = current[bit]
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/context.py", line 75, in __getitem__
app_1          |     raise KeyError(key)
app_1          | KeyError: 'do_rosetta'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 891, in _resolve_lookup
app_1          |     if isinstance(current, BaseContext) and getattr(type(current), bit):
app_1          | AttributeError: type object 'RequestContext' has no attribute 'do_rosetta'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 900, in _resolve_lookup
app_1          |     current = current[int(bit)]
app_1          | ValueError: invalid literal for int() with base 10: 'do_rosetta'
app_1          | 
app_1          | During handling of the above exception, another exception occurred:
app_1          | 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 907, in _resolve_lookup
app_1          |     (bit, current))  # missing attribute
```

It seems like do_django and do_rosetta are not provided to the template context any longer. This may be the reason why it throws the error in my logs. (it does not crash the views)

I can only find those variables in the `languages.html` template file:
https://github.com/mbi/django-rosetta/blob/052133fe176fd00cc2cd0ade84a1124d05bf926b/rosetta/templates/rosetta/languages.html#L43

I'm unfamiliar with the history of django-rosetta. So I'm not sure if it is safe to remove those variables (and their checks).

**Comment by mbi** [comment]
Good catch, thank you!
