### ISSUE TITLE
reverse_lazy() in settings.LOGIN_URL

### ISSUE THREAD

**Issue by eriktelepovsky** [mbi/django-rosetta#241]
- Which version of Django are you using?: **2.2.4**
- Which version of django-rosetta are you using?: **0.9.4**
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? **Yes**

Hi. When I set settings.LOGIN_URL to reverse_lazy() instead of simple string, I get following exception when the user is not logged in:

Exception:
```
Internal Server Error: /rosetta/files/project/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "django/contrib/auth/decorators.py", line 23, in _wrapped_view
    resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
  File "django/shortcuts.py", line 139, in resolve_url
    to = str(to)
TypeError: __str__ returned non-string (type __proxy__)
[19/Jun/2020 14:48:42] "GET /rosetta/files/project/ HTTP/1.1" 500 126407
```

URL:
```
http://127.0.0.1:8000/rosetta/files/project/
```

settings.py
```
LOGIN_URL = reverse_lazy('login_signup')
```

**Comment by eriktelepovsky** [comment]
Sorry, not a rosetta issue.

Solved by setting ``LOGIN_URL = 'login_signup'`` (without reverse_lazy)
